name: tests
on:
  pull_request
env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
  CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
  CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test:ci
  
